#端口配置
server:
  port: 8999

public-key: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIc+/bf68XzgluaAEy/PSEIKGa6iujuaCrFsRp8+sn37DthwO8OZXuAe4CJIuZutRYxzdZb62A2dkkg1t7ubn70CAwEAAQ==
spring:
  datasource:
    # 使用阿里的Druid连接池
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    druid:
      # 填写你数据库的url、登录名、密码和数据库名
      url: jdbc:mysql://42.193.174.46:3306/testdb?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
      username: testdb
      password: Agd00ggsOdOX7DpFPgvlkSphx5GWI5ObBVEhx5+CGEIsrpwmtZzLvHnJI5XVVBoowsnigv05lVEaKGrbnuUl8g==
      connectionProperties: config.decrypt=true;config.decrypt.key=${public-key};druid.stat.slowSqlMillis=5000;druid.stat.logSlowSql=true
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initialSize: 5
      min-idle: 5
      maxActive: 20
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      logAbandoned: true
      removeAbandoned: true
      removeAbandonedTimeout: 180
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      validationQuery: SELECT 'x'
      # 打开PSCache，并且指定每个连接上PSCache的大
      poolPreparedStatements: true
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      filters: config,stat,wall,slf4j
      use-global-data-source-stat: true
      # 配置DruidStatViewServlet
      stat-view-servlet:
        url-pattern: /druid/*
        login-username: admin
        login-password: admin
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow:
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 192.168.1.73
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: "/*"
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8